FROM eclipse-temurin:21.0.6_7-jdk-jammy

RUN mkdir -p /opt/sheng/app

COPY ./mi-proyecto-0.0.1-SNAPSHOT.jar /opt/sheng/app

EXPOSE 8080

WORKDIR /opt/sheng/app

CMD ["java", "-jar", "mi-proyecto-0.0.1-SNAPSHOT.jar"]