services:
  mariadbSheng:
    image: mariadb:lts-ubi9
    hostname: mariadbSheng
    volumes:
      - ./app:/var/lib/mysql
    ports:
      - "4000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    tty: true
    stdin_open: true
    pull_policy: never

  appSheng:
    image: mi_sheng_app:1.3
    hostname: appSheng
    ports:
      - "4001:2340"
    tty: true
    stdin_open: true
    pull_policy: never